#!/bin/sh
set -e

#DEBHELPER#

case "$1" in
    purge)
        rm -rf /etc/eth-validator-stats /var/lib/eth-validator-stats
        if getent passwd eth-validator-stats >/dev/null; then
            deluser --system --quiet eth-validator-stats || true
        fi
        ;;
esac

exit 0
